### ISSUE TITLE
Unable to import SAP Cloud Foundry SAML 2.0 Auth Flow policy

### ISSUE THREAD

**Issue by socenmarc** [SAP-samples/apibusinesshub-api-recipes#7]
Hi @aadinigam,

I'm importing the SAP Cloud Foundry SAML 2.0 Auth Flow policy via zip file and I get the following error:
> Invalid ID; ID can only contain alphanumeric characters, underscore(_) and hyphen(-).

> Invalid ID; ID can only contain alphanumeric characters, underscore(_) and hyphen(-).[Request ID: 908984e1-2fbe-405d-be28-ee4e89986d20] 

![Capture](https://user-images.githubusercontent.com/11246514/70703776-0d978d80-1cd1-11ea-9add-015ac98b3c68.PNG)

I'm in API Portal in a non-trial and successfully on boarded account (supposedly).

Additional info:
I'm importing the policy because I can't copy it from Discover. When doing so, I get an error because it already exists in my policies although it does not exist: (I'm going to create an oss ticket for this issue.)
![Capture2](https://user-images.githubusercontent.com/11246514/70704777-f9ed2680-1cd2-11ea-9caa-efee07eefc01.png)
![Capture3](https://user-images.githubusercontent.com/11246514/70704819-112c1400-1cd3-11ea-9729-bbdbb51e2c02.PNG)
![Capture4](https://user-images.githubusercontent.com/11246514/70704892-33259680-1cd3-11ea-95e3-0213df3442fa.PNG)

Thanks in advance,
Marc

**Comment by kulkarnir** [comment]
Hi Marc, 

Thanks for sharing, we will look into this and update.

Please try workaround, which will help you to import the policy template  

1)  Unzip and open the file SAPCloudFoundrySAML2OAuthFlow.xml

<img width="406" alt="image" src="https://user-images.githubusercontent.com/26405634/70795455-d8b93280-1dc5-11ea-8b8f-f4424c79f286.png">

2) Please update the name tag as shown in screenshot
     Name : SAP Cloud Foundry SAML2OAuth Flow
     work around update : SAP_Cloud_Foundry_SAML2OAuth_Flow

<img width="423" alt="image" src="https://user-images.githubusercontent.com/26405634/70795663-58470180-1dc6-11ea-8eb2-770919877afa.png">

3) Now zip and try to import, this should work..
     Please take care of folder structure when you zip

Regards, 
Raghavendra Kulkarni

**Comment by socenmarc** [comment]
Hi Raghavendra,

thanks for the workaround. It works fine.

Regards,
Marc
